// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: internal/kgs/service.proto

package kgs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KGS_GetKey_FullMethodName = "/kgs.KGS/GetKey"
)

// KGSClient is the client API for KGS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KGSClient interface {
	// GetKey returns a single fresh key.
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
}

type kGSClient struct {
	cc grpc.ClientConnInterface
}

func NewKGSClient(cc grpc.ClientConnInterface) KGSClient {
	return &kGSClient{cc}
}

func (c *kGSClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KGS_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KGSServer is the server API for KGS service.
// All implementations must embed UnimplementedKGSServer
// for forward compatibility.
type KGSServer interface {
	// GetKey returns a single fresh key.
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	mustEmbedUnimplementedKGSServer()
}

// UnimplementedKGSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKGSServer struct{}

func (UnimplementedKGSServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKGSServer) mustEmbedUnimplementedKGSServer() {}
func (UnimplementedKGSServer) testEmbeddedByValue()             {}

// UnsafeKGSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KGSServer will
// result in compilation errors.
type UnsafeKGSServer interface {
	mustEmbedUnimplementedKGSServer()
}

func RegisterKGSServer(s grpc.ServiceRegistrar, srv KGSServer) {
	// If the following call panics, it indicates UnimplementedKGSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KGS_ServiceDesc, srv)
}

func _KGS_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KGSServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KGS_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KGSServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KGS_ServiceDesc is the grpc.ServiceDesc for KGS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KGS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kgs.KGS",
	HandlerType: (*KGSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _KGS_GetKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/kgs/service.proto",
}
